### ISSUE TITLE
xaplimxapleq esta muito amostradinho la ele

### ISSUE THREAD

**Issue by Illumimatt** [Eduardoxaplim/programacao_web_b_lobo#1]
bora billsson la elons

**Comment by Eduardoxaplim** [comment]
lá ele mil vezes kkkk

**Comment by Illumimatt** [comment]
problema resolvido.

**Comment by Juuia** [comment]
só os casca de bala aqui, aqueles cara

**Comment by Carololivert** [comment]
i o ouru ve nunjk?

**Comment by Illumimatt** [comment]
⠉⠀⠈⠁⠀⠀⠙⢧⡈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⠀⠀⠀⠀⠁⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⡿⠿⠿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣄⣀⣠⣶⣶⣶⣶⣶⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⠋⠁⠀⠀⠀⠀⠀⠈⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⠇⠀⢀⡴⠀⠀⠀⠀⠀⠀⠈⠛⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⡿⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠐⢼⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⠟⢁⣤⠶⢊⣠⣶⣿⣷⠀⠀⠀⢀⡀⠀⠀⢹⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⡷⠚⣉⣤⣶⣿⣿⣿⣿⠇⠀⠘⣰⣿⣷⡀⠀⠈⠁⣹⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⠃⢠⣾⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⣿⣿⣿⣧⠀⠀⠀⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⡀⠘⢿⣿⣿⣿⡿⠟⢁⡄⠀⠀⠀⣿⣿⣿⣿⣆⠀⠀⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⢀⡤⠖⠁⠀⠀⠀⠀⢻⣿⣿⣿⣿⣆⠀⠸⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣤⠄⠀⠈⠀⣴⣦⣾⣿⣦⠀⠀⠈⠻⣿⣿⣿⣿⡆⠀⠹⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠈⠛⠛⠛⠿⠇⠀⠀⠀⠈⠉⠉⠉⠀⠀⢠⣿⣿
⢿⣿⣿⠛⠿⠿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⣄⠀⠀⠀⠀⣠⣿⣿⣿
⠀⠀⢹⠀⠀⠀⠀⠀⣟⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣿⣿⣿⠁⡔⣡⣾⣿⣿⣷⣶⣄⠀⠀⠀⠀⠀⠈⢩⣿⣿⣿⣿⣿⣿
⠀⠀⠸⠀⠀⠀⠀⢀⠸⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣼⢱⣿⣿⣿⣿⣿⣿⣿⡆⠀⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⠀⠀⠀⠀⡘⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿
⣤⣤⣤⠀⠀⠀⠀⠁⢀⡀⠀⠀⠀⠀⢀⣰⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⠀⠀⠀⠀⠀⢸⣿⣷⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿⣿⣿⣿⣿⣿⡟⠀⣀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⠀⠀⠀⢀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿⣿⣿⣿⡿⢁⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⡀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢸⣿⣿⣿⣿⣿⢁⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⡇⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⣼⣿⣿⣿⣿⠃⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣧⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⣿⣿⣿⣿⠃⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡄⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠙⠿⠟⢃⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣄⡀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

HUMMM EU GOSTO É ASSIM, AMOSTRADINHO GRUPINHO

**Comment by Juuia** [comment]
kkkkk receba pai, vapo

**Comment by Carololivert** [comment]
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ 
⣿⣿⠄⢀⣀⣀⣀⣀⠄⢀⣀⣀⣀⠄⢀⣀⣀⣀⡀⠄⣀⣀⣀⣀⡀⠄⣿⣿ 
⣿⣿⠄⢸⣿⣉⣉⣉⠄⢸⣉⣉⣹⡇⢸⣏⣉⣉⠁⠄⣿⡏⠉⠛⠃⠄⣿⣿ 
⣿⣿⠄⢠⣤⣤⣼⡿⠄⢸⠄⠄⠄⠄⢸⡇⠄⠄⠄⠄⣿⣧⣤⣿⠇⠄⣿⣿ 
⣿⣿⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣿⣿ 
⣿⡻⣯⡉⠉⠉⠉⠉⠉⠉⠉⠉⣿⣿⣿⣿⠉⠉⠉⠉⠉⠉⠉⠉⢉⣽⢟⣿ 
⣿⣿⡿⣷⣄⠄⠄⠄⠄⠄⠄⠄⣿⣿⣿⣿⠄⠄⠄⠄⠄⠄⠄⣠⣾⢿⣿⣿ 
⣿⣿⣿⣷⡿⣷⡀⠄⠄⠄⠄⠄⣿⣿⣿⣿⠄⠄⠄⠄⠄⢀⣾⢿⣾⣿⣿⣿ 
⣿⣿⣿⣿⣿⣮⣿⣆⠄⠄⠄⠄⣿⣿⣿⣿⠄⠄⠄⠄⣰⣿⣵⣿⣿⣿⣿⣿ 
⣿⣿⣿⣿⣿⣿⣷⣝⢿⣆⠄⠄⣿⣿⣿⣿⠄⠄⣰⡿⣫⣾⣿⣿⣿⣿⣿⣿ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡻⣦⠄⣿⣿⣿⣿⠄⣴⢟⣿⣿⣿⣿⣿⣿⣿⣿⣿ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⢿⣿⣿⣿⣿⡿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

**Comment by Carololivert** [comment]
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣥⣤⣾⠟⡛⠿⠿⣭⣻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡟⣿⣽⡟⡏⢩⣦⡝⠋⢸⣶⠄⢲⡟⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣯⣷⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣌⡳⣜⢿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢀⡛⢌⢿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠄⠙⠌⣸⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡿⠉⠉⠉⠉⢿⣿⣿⣿⠏⠉⠉⠉⠉⠉⠆⠄⠁⠄⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡗⠫⠿⠆⠄⠸⢿⣿⣿⠂⠒⠲⡿⠛⠛⠂⠄⠄⢠⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡛⣧⡔⠢⠴⣃⣠⣼⣿⣧⡀⠘⢢⣀⠄⠄⠄⠄⠄⢈⠁⢿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣿⠄⠄⠄⣸⠆⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⣿⣼⢿⣿⣿⣿⣿⡀⠄⠘⡀⢠⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡌⠿⣫⣿⣦⠬⢭⣥⣶⣬⣾⣿⢿⣿⡟⠄⢀⣿⣶⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣧⠘⣉⠛⢻⣛⣛⣛⣻⡶⠮⠙⠃⣉⠄⠄⢸⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡆⠸⣿⣶⢾⣿⣯⣤⣄⣀⣾⡟⠄⠄⠄⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠟⠿⠿⠿⠿⢿⣷⠄⣿⣿⣎⣹⢻⣿⣿⡿⡿⠁⠄⠄⠄⢸⣿⣿⣿⣿⣿⣿⣿⣿
⠄⠄⠄⠄⠄⠄⠄⣠⠘⣿⣿⣿⣿⣿⣿⡟⠁⣀⣀⣀⠄⠘⠿⣿⣿⣿⣿⣿⣿⣿

**Comment by Carololivert** [comment]
Bei polizeilichen Ermittlungen erkläre ich offiziell, dass ich keine Beteiligung an dieser Gruppe haben und nicht wissen, wie ich es bin, ich wahrscheinlich von Dritten eingesetzt wurde, erklären, dass ich bereit bin, mit der Untersuchung mitzuarbeiten und bin bereit, mich wenn nötig Zeugnis einzuführen, ich erkläre, dass ich bin völlig unschuldig und habe keine Beteiligung mit diesem Fall nicht in diesem Beitrag gezeigt

**Comment by Juuia** [comment]
⠁⠁⠁⠁⠁⠁⠁⢀⣴⣶⣿⣿⣷⣶⣦⡀⠁⠁⠁⠁⠁⠁⠁⠁⠁⠁⠁⠁ ⠁⠁⠁⠁⠁⠁⠁⣠⣿⣿⣿⣿⣿⣿⣟⣿⣿⣧⣄⠁⠁⠁⠁⠁⠁⠁⠁⠁⠁ ⠁⠁⠁⠁⣠⣴⣾⣿⣿⣿⣿⣿⣿⣷⣿⣷⣿⣿⣿⣷⣦⣄⡀⠁⠁⠁⠁⠁⠁ ⢀⣠⠶⠿⠿⠛⠛⠛⠛⠛⠛⠉⠋⠉⠋⠙⠙⠋⠛⠛⠟⠿⠿⣷⣦⡀⠁⠁⠁ ⠘⠤⡁⡐⢀⠁⠁⡀⠂⢀⠁⢀⠁⠂⠁⡀⢀⠁⡀⢀⠁⠁⠁⠁⢉⡹⠁⠁⠁ ⠁⠁⠁⠁⠁⠄⣦⣾⡼⠁⣤⢄⠤⠠⠠⠄⢠⠁⡄⢠⢀⡢⠦⠁⠁⡀⠁⠁⠁ ⠁⠁⠁⠁⠁⠘⠥⡄⣀⠓⢍⢡⢃⡜⢰⠨⠦⠊⠈⠁⠁⢀⢀⠁⡌⢸⡇⠁⠁ ⠁⠁⠁⠁⠁⠁⠁⠁⠁⠉⠈⣠⣕⢀⢆⢑⡑⢤⣢⡀⠆⢐⠁⠁⢂⠜⠳⠶⡄ ⠁⠁⠁⠁⠁⠁⠁⢀⣀⠤⢾⡟⣫⠝⠖⡡⠃⠂⠠⠙⠲⠤⣀⠁⡁⢀⢂⡐⠃ ⠁⠁⠁⢀⣠⣴⢶⡏⠈⠁⣺⢞⡏⡝⠬⡠⢂⡘⣐⣤⠁⠁⠉⠢⣄⣀⡀⠁⠁ ⠁⠁⠁⡛⠁⠁⠁⠁⠁⠁⣿⣮⡧⣽⢶⣵⣿⣾⣧⣿⡦⠂⠁⠁⠠⠁⡎⡩⠁ ⠁⠁⠁⠈⠁⠁⠁⠁⠁⠁⠁⠘⠳⣻⣾⡿⡽⡧⣟⡝⢷⢖⣶⣄⠁⠁⠁⠁⠁ ⠁⠁⠁⠁⠁⠁⠁⠁⠁⣀⠁⠁⠁⣹⡿⣿⠟⠁⠁⣤⣿⢺⡆⡟⢧⠁⠁⠁⠁ ⠁⠁⠁⠁⠁⠁⠖⡛⠻⠛⠿⢟⢿⢻⡻⣯⠁⠁⠈⠛⠘⠁⠃⠑⠁⠁⠁⠁⠁ ⠁⠁⠁⠁⠁⠁⠁⠁⠁⠈⠁⠁⠁⠁⠁⠈⠁⠁⠁⠁⠁⠁⠁⠁⠁⠁⠁⠁⠁

INDO ALI

**Comment by Juuia** [comment]
FILL 🧨🧨🧨🧨🇧🇷🇧🇷🇧🇷🇧🇷✨ POW POW POW 🎇🎆🇧🇷🇧🇷💥💥🇧🇷🇧🇷🎇BRASIL BOOM✨🎆🎆🇧🇷🇧🇷🎉🎆TRATRATR🇧🇷🇧🇷💥🎆BRASIL FIIIIIU 🎆🇧🇷🇧🇷✨🎆🎆🧨🎆✨🎇POW POW 🎆🧨🎇PÁ PÁ ✨🇧🇷🇧🇷✨🎆🧨🎇✨🎇🇧🇷TRA TRA TRA TRA 💥💥 🇧🇷🇧🇷✨POW POW POW 🎇🎆💥🎇✨🎇🎆🧨🇧🇷🇧🇷

**Comment by Illumimatt** [comment]
Olá @Eduardoxaplim Sou eu, seu único espectador. Durante meses, criei a ilusão de que você está transmitindo para um grande público. Mas aqui está a verdade: todas essas pessoas no chat sou eu. E agora, para você se convencer disso,vou enviar esta mensagem de todas as minhas contas

**Comment by Juuia** [comment]
⠀⠀⠀⠀⠀⠀⢀⣠⣤⣤⣤⣤⣤⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⢀⣤⠞⢋⣁⣠⡤⠀⠀⠀⠀⠀⠨⠿⠿⢶⣶⣤⣄⠀⠀
⠀⠀⣴⢋⣥⡾⢛⣭⠶⠶⢤⡄⠀⠀⠀⠀⢠⡴⠛⢛⣿⣿⡃⠀
⠀⣸⠁⠉⠉⢠⡟⠀⠀⠀⠀⢹⡆⠀⠀⢠⡏⠀⠀⠈⠉⢸⡇⠀
⢀⡏⠀⠀⠀⢼⣇⢿⠿⠀⠀⣸⠇⠀⠀⠈⢧⣤⣀⣤⣤⣟⣷⠀
⢸⠃⠀⠀⠀⠀⠈⠛⠲⠶⠞⠁⠀⠀⢀⣀⣠⡼⢋⣤⢤⣌⠻⣆
⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠁⠀⣾⢁⡾⡗⡶⣾⡆⣿
⢸⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⡇⢸⠏⠉⠉⠉⡇⡿
⠘⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⢸⠀⠀⠀⣸⢱⡇
⠀⢹⡀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⢸⠀⠀⠀⡏⢸⡇
⠀⠈⣧⠀⠹⡀⠀⠀⠀⠀⠀⠀⠁⠀⠀⢠⡇⣿⠒⠤⡀⢿⠀⡇
⠀⠀⠘⣇⠀⠁⠀⠀⠀⠀⠐⠲⢤⡀⠀⣼⠀⣧⣤⣤⡼⣾⠀⡇
⠀⠀⠀⠘⢧⡀⠁⠀⠀⠀⠀⠀⠀⠈⠳⣿⠀⢿⡛⠻⣷⠏⢠⡇
⠀⠀⠀⠀⠀⠛⢦⣄⠀⠐⠢⠄⣀⠀⠀⠹⣦⡀⠉⠉⢉⣠⠏⠀
⠀⠀⠀⠀⠀⠀⠀⠉⠛⠶⢦⣄⡀⠀⠀⠀⢀⣉⡿⠟⠋⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠒⠚⠋⠁⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⡀⡀⠀⠀⠀⡀⠀⠀⠀⢀⣀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠃⠈⠊⠊⠈⠃⠂⠀⠃⠊⠊⠀⠈⠈⠑⠄⠀⠀⠀⠀⠀

hue hue hue hue hue hue  hue hue hue hue hue BR, hahaha quem lembra?
